-- Conventions: ids are text (nanoid), money is bigint minor units + currency text, timestamps timestamptz.
-- Every table carries created_at/updated_at; tables that hold state carry version int for optimistic concurrency.
-- Translate to Prisma models in packages/database; keep names.
-- 006 travel: flights, journeys, stays (flights-service, journey-service, stays-service)
create table airlines (code text primary key, name text, one_ticket_partner boolean default false, reclaim_agreement_ref text, reliability_score numeric);
create table flight_bookings (id text primary key, user_id text not null, journey_id text, airline_code text references airlines(code), flight_no text, depart_at timestamptz, arrive_at timestamptz, from_iata text, to_iata text, from_terminal text, pnr text, fare_minor bigint, currency text, passenger jsonb not null, status text not null, protection_active boolean default false, version int default 1, idempotency_key text unique, created_at timestamptz default now());
create table flight_status_watch (booking_id text primary key references flight_bookings(id), last_status text, delay_min int, last_polled timestamptz);
create table switches (id text primary key, booking_id text references flight_bookings(id), old_pnr text, new_pnr text, new_flight jsonb, list_fare_minor bigint, covered_minor bigint, actor text, entry_id text, created_at timestamptz default now());
create table reclaims (id text primary key, booking_id text references flight_bookings(id), airline_code text, amount_minor bigint, status text not null, filed_at timestamptz, recovered_at timestamptz, recovered_minor bigint);
create table desk_queue (id text primary key, airport text, booking_id text references flight_bookings(id), need text, assist_flags text[], status text, agent_id text, created_at timestamptz default now());
create table journeys (id text primary key, user_id text not null, status text not null, protection text default 'none', total_minor bigint, currency text, created_at timestamptz default now());
create table journey_legs (id text primary key, journey_id text references journeys(id), position int, type text check (type in ('ride','flight','stay')), ref text not null, depends_on text, starts_at timestamptz, status text not null, amount_minor bigint, retimed_by text);
create table reservations (id text primary key, user_id text not null, city_id text not null, pickup jsonb, dropoff jsonb, vehicle_class text, pickup_at timestamptz not null, arrive_by timestamptz, linked_booking_id text, driver_id text, status text not null, release_free_until timestamptz, fare_minor bigint, version int default 1);
create table hotels (id text primary key, name text, city_id text, address text, lat numeric, lng numeric, rating numeric, review_count int, channel_manager text, protection_terms_version text, protection_eligible boolean default false, status text);
create table hotel_staff (id text primary key, hotel_id text references hotels(id), user_id text, role text check (role in ('desk','manager','revenue')));
create table stay_bookings (id text primary key, user_id text not null, journey_id text, hotel_id text references hotels(id), room_type text, rate_id text, check_in date, check_out date, nights int, gross_minor bigint, tax_breakdown jsonb, currency text, payment_mode text, guarantee_token text, confirmation_code text, status text not null, protection text default 'none', prefs jsonb, room_no text, version int default 1, idempotency_key text unique, created_at timestamptz default now());
create table checkins (id text primary key, stay_booking_id text references stay_bookings(id), id_verified boolean, signature_ref text, completed_at timestamptz, desk_confirmed_at timestamptz);
create table eta_shares (id text primary key, stay_booking_id text references stay_bookings(id), ride_id text, eta timestamptz, expires_at timestamptz);
create table stay_protection_events (id text primary key, stay_booking_id text references stay_bookings(id), cause text check (cause in ('airline_delay','airline_cancel')), outcome text, cover_minor bigint, entry_id text, created_at timestamptz default now());
create table hotel_reviews (id text primary key, stay_booking_id text unique references stay_bookings(id), stars int, tags text[], text text, display_name text, published boolean default false, created_at timestamptz default now());
create table hotel_replies (review_id text primary key references hotel_reviews(id), text text, by_user text, created_at timestamptz default now());
