# =============================================================================
# Monitoring Stack Application
# =============================================================================
# Deploys Prometheus, Grafana, and related monitoring tools
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: ubi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ubi

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.1
    helm:
      releaseName: prometheus
      values: |
        fullnameOverride: prometheus

        # Prometheus configuration
        prometheus:
          prometheusSpec:
            retention: 15d
            retentionSize: 45GB
            
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: 2
                memory: 8Gi
            
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp3
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
            
            # Service discovery for UBI services
            serviceMonitorSelector:
              matchLabels:
                app.kubernetes.io/part-of: ubi
            
            # Additional scrape configs for custom metrics
            additionalScrapeConfigs:
              - job_name: 'ubi-services'
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - ubi-apps
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    action: keep
                    regex: true
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                    action: replace
                    target_label: __metrics_path__
                    regex: (.+)
                  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                    action: replace
                    regex: ([^:]+)(?::\d+)?;(\d+)
                    replacement: $1:$2
                    target_label: __address__

        # Grafana configuration
        grafana:
          enabled: true
          adminPassword: "" # Use secret
          
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: gp3
          
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          
          # UBI dashboards
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: 'ubi'
                  orgId: 1
                  folder: 'UBI'
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/ubi
          
          # Data sources
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://prometheus-prometheus:9090
                  access: proxy
                  isDefault: true
                - name: Loki
                  type: loki
                  url: http://loki:3100
                  access: proxy
                - name: Jaeger
                  type: jaeger
                  url: http://jaeger-query:16686
                  access: proxy
          
          # Grafana plugins
          plugins:
            - grafana-piechart-panel
            - grafana-clock-panel
            - grafana-worldmap-panel

        # Alertmanager configuration
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp3
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
          
          config:
            global:
              resolve_timeout: 5m
            
            route:
              group_by: ['alertname', 'severity']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 4h
              receiver: 'default'
              routes:
                - match:
                    severity: critical
                  receiver: 'critical'
                - match:
                    severity: warning
                  receiver: 'warning'
            
            receivers:
              - name: 'default'
                # Configure in overlay
              - name: 'critical'
                # Configure in overlay
              - name: 'warning'
                # Configure in overlay

        # Node exporter
        nodeExporter:
          enabled: true

        # Kube state metrics
        kubeStateMetrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ubi-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# Loki for log aggregation
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: ubi
spec:
  project: ubi

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.41.4
    helm:
      releaseName: loki
      values: |
        loki:
          auth_enabled: false
          
          commonConfig:
            replication_factor: 1
          
          storage:
            type: s3
            bucketNames:
              chunks: ubi-${ENVIRONMENT}-loki-chunks
              ruler: ubi-${ENVIRONMENT}-loki-ruler
              admin: ubi-${ENVIRONMENT}-loki-admin
            s3:
              region: af-south-1
          
          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: s3
                schema: v12
                index:
                  prefix: index_
                  period: 24h

        singleBinary:
          replicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: ubi-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# OpenTelemetry Collector
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: ubi
spec:
  project: ubi

  source:
    repoURL: https://github.com/ubi-africa/ubi-monorepo.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/monitoring/otel-collector

  destination:
    server: https://kubernetes.default.svc
    namespace: ubi-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Jaeger for distributed tracing
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: ubi
spec:
  project: ubi

  source:
    repoURL: https://github.com/ubi-africa/ubi-monorepo.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/monitoring/jaeger

  destination:
    server: https://kubernetes.default.svc
    namespace: ubi-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
